### ISSUE TITLE
Support of JSON-LD framing

### ISSUE THREAD

**Issue by brechtvdv** [Informatievlaanderen/VSDS-Linked-Data-Interactions#354]
We would like to use LDIO (or NIFI) for the following pipeline:
LDES client -> SPARQL construct to transform to NGSI-LD model -> serialize as JSON-LD with frame -> HTTP POST / Kafka

Currently, HTTP out or Kafka out allow to set JSON-LD as content-type, but it is not possible to define a JSON-LD frame.
This means that we cannot send an NGSI-LD compliant JSON-LD towards a context broker.

I see two options (as discussed with @ranko):
- LDIO: Add a framing option to the Out connectors
- Nifi: have a generic serialization connector that can parse and serialize (with framing)

**Comment by brechtvdv** [comment]
Preference for Kafka-out, and HTTP-out to have this option

**Comment by brechtvdv** [comment]
I see frame-type is added, but we also need to set the JSON-LD context.
Why not give flexibility to define a complete JSON-LD frame?

**Comment by Yalz** [comment]
@brechtvdv as part of the 1.8.0 release coming in the next days, the JSON-LD framing has been expanded so that the whole JSON-LD frame can be included. For more details, feel free to take a look at the [LDIO RDF writer docs](https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/ldio-core/ldio-rdf-writer)
