### ISSUE TITLE
Check if client uses compression

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-Linked-Data-Interactions#580]
Verify that the client asks for gzipped content

**Comment by jobulcke** [comment]
The Client does not ask for gzipped content. In addition, I did a little investigation and for some reason, the default way to turn gzip compression on on a Spring Boot server, does not work on the LdesServer. Thus, before letting the client ask for gzipped content, this should be fixed in the server, probably with an implementation of a so called filter. 

As this would be a new feature, with a small effort probably, I would move this to JIRA
